import { Link } from "react-router-dom";
import useBackNav from "../utils/useBackNav";

const LAST_UPDATED = "8 July 2026";
const CEO_NAME = "Eli Tamuno-Owunari Tamunosiki";

export default function TermsOfService() {
  const back = useBackNav();

  return (
    <div style={s.page}>
      <div style={s.container}>
        <button style={s.back} onClick={() => back()}>← Back</button>
        <h1 style={s.title}>Terms of Service</h1>
        <p style={s.updated}>Last updated: {LAST_UPDATED}</p>

        <div style={s.notice}>
          📌 This document is a draft prepared to get Scholars Syndicate operating with clear,
          reasonable terms. It is <strong>not a substitute for review by a licensed Nigerian
          lawyer</strong> — particularly given that this app processes payments and personal
          data from users who are largely minors. Please have it reviewed before relying on it
          to limit liability in a dispute.
        </div>

        <Section title="1. Who we are">
          <p>
            Scholars Syndicate ("the App", "we", "us") is an exam-preparation platform for
            Nigerian students preparing for JAMB/UTME, Post-UTME, WAEC, and NECO examinations.
            The App is owned and operated under the leadership of its Chief Executive Officer,
            <strong> {CEO_NAME}</strong>.
          </p>
          <p>
            Scholars Syndicate is an independent, privately built platform. It is{" "}
            <strong>not affiliated with, endorsed by, or operated on behalf of</strong> the Joint
            Admissions and Matriculation Board (JAMB), the West African Examinations Council
            (WAEC), the National Examinations Council (NECO), or any Nigerian tertiary
            institution. References to these bodies and their examinations are made solely to
            describe what the App helps you study for.
          </p>
        </Section>

        <Section title="2. Accepting these terms">
          <p>
            By creating an account or using the App, you agree to these Terms. If you do not
            agree, please do not use the App. We may update these Terms from time to time (see
            Section 13) — continued use after an update means you accept the revised Terms.
          </p>
        </Section>

        <Section title="3. Who can use the App — and a note for users under 18">
          <p>
            Most JAMB and WAEC/NECO candidates are minors. You may use the App if you are old
            enough to hold this kind of account under Nigerian law, or if a parent or guardian
            has agreed to these Terms on your behalf.
          </p>
          <ul style={s.list}>
            <li>If you are under 18, we ask that a parent or guardian be aware of and approve
              your use of the App, particularly before any purchase is made (see Section 6).</li>
            <li>The App includes a Parent Access feature specifically so a parent/guardian can
              review a minor's activity and progress.</li>
            <li>We do not knowingly collect more personal information from a minor than is
              needed to provide the service (name, school, exam details, and performance data).</li>
          </ul>
        </Section>

        <Section title="4. Your account">
          <p>You're responsible for:</p>
          <ul style={s.list}>
            <li>Providing accurate registration information (name, email, phone, school).</li>
            <li>Keeping your password confidential and secure.</li>
            <li>All activity that happens under your account — tell us immediately at the
              contact below if you believe your account has been compromised.</li>
          </ul>
        </Section>

        <Section title="5. What the App provides">
          <p>
            Practice questions, timed mock exams, flashcards, an AI tutor and AI-generated
            practice questions, performance tracking, a predicted-score estimate, gamified
            features (Arena, Factions, Spirits, leaderboards, etc.), and reference tools like
            the Cut-Off Mark Tracker.
          </p>
          <p style={s.callout}>
            ⚠️ <strong>AI-generated content disclaimer.</strong> Some questions, explanations,
            and tutor responses are generated by third-party AI models (currently Groq and
            Google Gemini). AI output can contain mistakes — wrong answers, made-up
            "explanations," or content that doesn't match the current official syllabus. Use it
            as a study aid, not as an authoritative source. Always cross-check important facts
            against your official JAMB/WAEC syllabus or a teacher. The predicted-score feature
            and Cut-Off Mark Tracker are estimates for planning purposes only — they do not
            guarantee any exam result or admission outcome, and cutoff figures should always be
            confirmed on the official JAMB CAPS portal before you make an application decision.
          </p>
        </Section>

        <Section title="6. Tokens, Gems, subscriptions, and payments">
          <ul style={s.list}>
            <li><strong>Tokens</strong> and <strong>Gems</strong> are virtual in-app currencies
              with no cash value outside the App. They cannot be exchanged for real money,
              transferred to another person, or redeemed anywhere outside Scholars Syndicate.</li>
            <li>Payments are processed by Paystack. We do not store your full card details.</li>
            <li>Purchases of tokens, gems, or a premium subscription are generally
              <strong> non-refundable</strong> once the tokens/gems have been credited or the
              subscription period has started, except where required by Nigerian consumer
              protection law, or where we made an error (e.g. a payment was charged twice due to
              a technical fault — see below).</li>
            <li>If you believe you were wrongly charged (e.g. charged more than once for the
              same purchase, or charged without receiving the tokens/gems/subscription), contact
              us at the email below with your payment reference and we will investigate.</li>
            <li>We may offer promotions, referral bonuses, or free token grants at our
              discretion; these can be changed or withdrawn at any time going forward (not
              retroactively removed from your existing balance without cause).</li>
          </ul>
        </Section>

        <Section title="7. Acceptable use">
          <p>Please don't:</p>
          <ul style={s.list}>
            <li>Use bots, scripts, or automated tools to farm tokens, XP, or leaderboard
              rankings, or to extract questions/answers in bulk.</li>
            <li>Attempt to access another user's account, or data you're not authorized to see.</li>
            <li>Harass, bully, or send abusive content to other users in Squad Chat, Faction
              chat, or any social feature.</li>
            <li>Attempt to interfere with, disrupt, or reverse-engineer the App's security,
              grading, or payment systems.</li>
          </ul>
          <p>
            We may suspend or terminate accounts that violate this section, especially anything
            involving payment fraud or attempts to cheat the exam-grading or leaderboard systems.
          </p>
        </Section>

        <Section title="8. Intellectual property">
          <p>
            The App's design, original question content, software, and branding belong to
            Scholars Syndicate. You're granted a personal, non-transferable license to use the
            App for your own exam preparation — not to copy, resell, or redistribute its content.
          </p>
          <p>
            "JAMB", "UTME", "WAEC", and "NECO" are marks of their respective owners and are used
            here descriptively, not to claim any affiliation (see Section 1).
          </p>
        </Section>

        <Section title="9. Data & privacy">
          <p>
            We collect the personal data needed to run the service — your registration details,
            exam/practice performance, and payment records (via Paystack). We process this data
            in line with the Nigeria Data Protection Act (NDPA) 2023. We don't sell your
            personal data to third parties.
          </p>
          <p>
            A full, standalone Privacy Policy detailing exactly what we collect, how long we
            keep it, and how you can request its deletion should be published alongside this
            document — this section is a summary, not a replacement for it.
          </p>
        </Section>

        <Section title="10. Disclaimers and limitation of liability">
          <p>
            The App is provided "as is." We work to keep content accurate and the service
            available, but we don't guarantee the App will be error-free, uninterrupted, or that
            using it will result in any particular exam score or admission outcome. To the
            extent permitted by Nigerian law, Scholars Syndicate and {CEO_NAME} are not liable
            for indirect losses arising from use of the App, including reliance on AI-generated
            content, predicted scores, or cutoff-mark estimates for real-world decisions.
          </p>
        </Section>

        <Section title="11. Termination">
          <p>
            You may stop using the App and request account deletion at any time. We may suspend
            or terminate accounts that violate Section 7, or where required by law. Purchased
            tokens/gems tied to a terminated account for cause are not refunded.
          </p>
        </Section>

        <Section title="12. Governing law">
          <p>These Terms are governed by the laws of the Federal Republic of Nigeria.</p>
        </Section>

        <Section title="13. Changes to these Terms">
          <p>
            We may update these Terms as the App evolves. Material changes will be reflected by
            updating the "Last updated" date above; where required by law, we'll provide more
            direct notice (e.g. in-app or by email).
          </p>
        </Section>

        <Section title="14. Contact">
          <p>
            Questions about these Terms, or requests regarding your data, can be sent to the
            Scholars Syndicate support contact provided in the App.
          </p>
          <p style={{ marginTop: 10 }}>
            <strong>{CEO_NAME}</strong><br />
            Chief Executive Officer, Scholars Syndicate
          </p>
        </Section>

        <p style={{ textAlign: "center", marginTop: 30 }}>
          <Link to="/register" style={{ color: "#6c63ff", fontWeight: 700, textDecoration: "none" }}>
            ← Back to registration
          </Link>
        </p>
      </div>
    </div>
  );
}

function Section({ title, children }) {
  return (
    <div style={s.section}>
      <h2 style={s.h2}>{title}</h2>
      {children}
    </div>
  );
}

const s = {
  page:      { minHeight: "100vh", background: "var(--bg)", fontFamily: "'Plus Jakarta Sans',sans-serif", padding: 16 },
  container: { maxWidth: 680, margin: "0 auto", paddingBottom: 40 },
  back:      { background: "none", border: "none", color: "#6c63ff", fontWeight: 700, cursor: "pointer", fontSize: 14, marginBottom: 12 },
  title:     { fontSize: 26, fontWeight: 900, color: "var(--text)", marginBottom: 2 },
  updated:   { fontSize: 12, color: "var(--text-muted)", marginBottom: 18 },
  notice:    { background: "rgba(253,203,110,0.12)", border: "1px solid rgba(253,203,110,0.35)", borderRadius: 12, padding: "12px 14px", fontSize: 12.5, lineHeight: 1.6, color: "#b7860b", marginBottom: 20 },
  section:   { marginBottom: 22 },
  h2:        { fontSize: 15, fontWeight: 800, color: "var(--text)", marginBottom: 8 },
  list:      { paddingLeft: 20, color: "var(--text-muted)", fontSize: 13.5, lineHeight: 1.8, margin: "8px 0" },
  callout:   { background: "rgba(108,99,255,0.08)", border: "1px solid rgba(108,99,255,0.25)", borderRadius: 10, padding: "10px 12px", fontSize: 13, lineHeight: 1.7, color: "var(--text)" },
};
